In [2]:
import torch
a = torch.rand(4,3,384,384)
pic_list= a.chunk(4,dim=0)
print(pic_list[0].shape)

torch.Size([1, 3, 384, 384])


In [ ]:
import torch
import torch.nn.functional as func
import numpy as np
word_prob = torch.rand()
caption = torch.rand()
word_size = 30522
ref_words = caption.index_select(-1, index=torch.arange(word_size).long())
word_loss = func.nll_loss(word_prob.log(), ref_words, reduction='none')
mask = (ref_words > 0.5).float()
word_loss = word_loss.mul(mask).sum().div(mask.sum())
print(word_loss)
        

In [18]:
import matchzoo as mz
import pandas as pd
# import re  # 这个可以不用
from sklearn import preprocessing  # 用于正则化
import numpy as np 
preprocessor = mz.preprocessors.BasicPreprocessor() 

ImportError: cannot import name 'Layer' from 'keras.engine' (/home/fxy0913@corp.sse.tongji.edu.cn/.conda/envs/blip/lib/python3.9/site-packages/keras/engine/__init__.py)

In [2]:
import torch 
import torch.nn as nn


class DSSM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, dropout):
        super(DSSM, self).__init__()
        self.embed = nn.Embedding(vocab_size, embedding_dim)
        self.fc1 = nn.Linear(embedding_dim, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 64)
        self.dropout = nn.Dropout(dropout)

    def forward(self, a, b):
        a = self.embed(a).sum(1)
        b = self.embed(b).sum(1)

        a = self.dropout(torch.tanh(self.fc1(a)))
        a = self.dropout(torch.tanh(self.fc2(a)))
        a = self.dropout(torch.tanh(self.fc3(a)))

        b = self.dropout(torch.tanh(self.fc1(b)))
        b = self.dropout(torch.tanh(self.fc2(b)))
        b = self.dropout(torch.tanh(self.fc3(b)))

        cosine = torch.cosine_similarity(a, b, dim=1, eps=1e-8)   # 计算两个句子的余弦相似度
        return cosine
    
    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                torch.nn.init.xavier_uniform_(m.weight)





/home/fxy0913@corp.sse.tongji.edu.cn/.conda/envs/blip/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [17]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
text1 = tokenizer('this is a model of mine', padding='longest', truncation=True, max_length=40, return_tensors="pt")
text2 = tokenizer('this is a model of mine', padding='longest', truncation=True, max_length=40, return_tensors="pt")
print(text1.input_ids)
print(text2.input_ids)
model = DSSM(30522, 10, 0.2)
model._init_weights()
print(model(text1.input_ids,text2.input_ids))

tensor([[ 101, 2023, 2003, 1037, 2944, 1997, 3067,  102]])
tensor([[ 101, 2023, 2003, 1037, 2944, 1997, 3067,  102]])
tensor([0.4829], grad_fn=<DivBackward0>)


In [9]:
caption = ['12345','122222','11111']
print(caption[0])

12345


In [14]:
from torch.nn import CrossEntropyLoss
from torch import tensor
labels = [tensor([[-100,255,455,555,677,344,342]]),tensor([[-100,255,455,555,677,344,342]])]
a = torch.rand(1,6,30524)
for label in labels:
    label = label[:,1:].contiguous()
    print(label)
    loss_fct = CrossEntropyLoss(reduction='mean', label_smoothing=0.1) 
    now_lm_loss = loss_fct(a.view(-1, 30524), label.view(-1))
    print(now_lm_loss.item())



tensor([[255, 455, 555, 677, 344, 342]])
10.448413848876953
tensor([[255, 455, 555, 677, 344, 342]])
10.448413848876953


In [23]:
from torch import tensor
import torch.nn.functional as F
a = torch.rand(1,6,30524)
c = torch.rand(1,8,30524)
print(a)
b = a[:,-1,:]
d = c[:,-1,:]
print(b)
b = torch.max (a,-1)
print(b)
print(b.indices.shape)
# c = torch.rand(1,5)
output = F.cosine_similarity(b,d)
print(output)
# print(b.shape)

tensor([[[0.9617, 0.5146, 0.6185,  ..., 0.6572, 0.3220, 0.3595],
         [0.3750, 0.4365, 0.5038,  ..., 0.9376, 0.1313, 0.9504],
         [0.0683, 0.3482, 0.0624,  ..., 0.2913, 0.2217, 0.5876],
         [0.8739, 0.5754, 0.0263,  ..., 0.9023, 0.8690, 0.2734],
         [0.2546, 0.7448, 0.9309,  ..., 0.0196, 0.4552, 0.4213],
         [0.9455, 0.9872, 0.4324,  ..., 0.7653, 0.6303, 0.4057]]])
tensor([[0.9455, 0.9872, 0.4324,  ..., 0.7653, 0.6303, 0.4057]])
torch.return_types.max(
values=tensor([[1.0000, 0.9999, 1.0000, 1.0000, 1.0000, 1.0000]]),
indices=tensor([[19737, 20779,  6671, 29534,  7956, 27947]]))
torch.Size([1, 6])


TypeError: cosine_similarity(): argument 'x1' (position 1) must be Tensor, not torch.return_types.max

In [1]:
import torch
from torch import tensor
label = tensor([[2551,2158,2012,25963,4713,102]])
shaped_prediction_score = torch.rand(1,6,30524)
score = shaped_prediction_score.view(-1,30524)


def self_loss(score,):


NameError: name 'tensor' is not defined

In [11]:
for content in caption:
    # print(i)
    print(content)

12345
122222
11111


In [8]:
from torch import tensor
import torch
a = tensor([[  101,  7661,  8917,  1106,  1103,  2394,  1107,  3461,   102,     0],
        [  101,  1109,  2084, 18884,  1116,  1103,  3181,  1107,  2290,   102],
        [  101,  6309,  1116,  1132,  1139,  5095,  5735,   102,     0,     0]])
print(a.shape)
# print(torch.split(a,[1,a.shape[1],a.shape[-1]],dim=0))
print(a[1])

torch.Size([3, 10])
tensor([  101,  1109,  2084, 18884,  1116,  1103,  3181,  1107,  2290,   102])


In [25]:
import torch.nn.functional as F
result1 = torch.randn(1,9,30524)
result2 = torch.randn(1,9,30524)
result3 = torch.randn(1,9,30524)
res_list = []
res_list.append(torch.max(result1,-1).indices)
res_list.append(torch.max(result2,-1).indices)
res_list.append(torch.max(result3,-1).indices)
print(res_list)
all_reg_loss_list = []
main_idx = 0
for main_idx in range(0,len(res_list)):
    print(main_idx)
    mainTensor = res_list[main_idx]
    for res_new in res_list[main_idx+1:]:
        print("inside")
        print(res_new)
        output = F.cosine_similarity(mainTensor.float(),res_new.float())
        print(output)
        # print(tensor.sum(output,1))
        # print(output)
        all_reg_loss_list.append(output)
print(all_reg_loss_list)
sum_reg_loss = torch.zeros_like(all_reg_loss_list[0])
for reg_loss in all_reg_loss_list:
    sum_reg_loss += reg_loss
print(sum_reg_loss)


[tensor([[10094, 13308, 27979, 27243,  5266, 22096, 19693, 13603, 26285]]), tensor([[18413,  2657, 21581, 16733,    86, 22866, 11966, 27904, 14086]]), tensor([[16133,  7627, 19829, 10808, 23843, 21130, 29533, 14019, 28984]])]
0
inside
tensor([[18413,  2657, 21581, 16733,    86, 22866, 11966, 27904, 14086]])
tensor([0.8855])
inside
tensor([[16133,  7627, 19829, 10808, 23843, 21130, 29533, 14019, 28984]])
tensor([0.8836])
1
inside
tensor([[16133,  7627, 19829, 10808, 23843, 21130, 29533, 14019, 28984]])
tensor([0.8004])
2
[tensor([0.8855]), tensor([0.8836]), tensor([0.8004])]


In [36]:
a = torch.ones([1,9,30524])
b = torch.ones([1,9,30524])
b = torch.cat([a,b],0)
a = tensor([10121])
b = tensor([123])
print(a/21)
print(b.size())
# print(b[1].size())
print(torch.cat([a,b]))

tensor([481.9524])
torch.Size([1])
tensor([10121,   123])


In [38]:
# a = tensor([1,2])
# print(a.item())


ValueError: only one element tensors can be converted to Python scalars

In [2]:
import torch
from torch import tensor
import json
def delete_duplicate(data):
    immutable_dict = set([str(item) for item in data])
    data = [eval(i) for i in immutable_dict]
    return data
def unique_dicts(data_list: list):
    data_json_set = set(json.dumps(item) for item in data_list)
    return [json.loads(item) for item in data_json_set]

print("a = ", a) 
#a = [{'image_id': 0,'phrase_list':[{'caption':'data','tensor':a},{'caption':'data','tensor':a},{'caption':'data1','tensor':a}]},]
a = [a,a,a,a,a,a,tensor([[1,2,3,4]])]
b = list(set(a))
# b = delete_duplicate(a[0]['phrase_list'])
print(b)

a =  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.

In [8]:
import numpy as np
import torch
from torch import tensor
import json
a = torch.ones([1, 577]) 
a[0][0]=0
a[0][123]=0
a[0][257]=0
a_list=[]
b_list=[]
bnew={"caption":"hhhh","tensor":a.numpy().tolist()}
b_list.append(bnew)
b_list.append(bnew)
a_list.append({"image_id":245,"phrase_list":b_list})
print(a.numpy().tolist())
with open("1.json","w") as f1:
    json.dump(a_list,f1)
with open("1.json","r") as f:
    nwe = json.load(f)
print(torch.from_numpy(np.array(nwe[0]["phrase_list"][0]["tensor"])))

[[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0

In [14]:
a = torch.ones([2, 1, 577]) 
a_list.append(a)
a_list.append(a)
a_list.append(a)
print(a_list[1][0].size())

torch.Size([1, 577])
