In [2]:
import torch
a = torch.rand(4,3,384,384)
pic_list= a.chunk(4,dim=0)
print(pic_list[0].shape)

torch.Size([1, 3, 384, 384])


In [ ]:
import torch
import torch.nn.functional as func
import numpy as np
word_prob = torch.rand()
caption = torch.rand()
word_size = 30522
ref_words = caption.index_select(-1, index=torch.arange(word_size).long())
word_loss = func.nll_loss(word_prob.log(), ref_words, reduction='none')
mask = (ref_words > 0.5).float()
word_loss = word_loss.mul(mask).sum().div(mask.sum())
print(word_loss)
        

In [18]:
import matchzoo as mz
import pandas as pd
# import re  # 这个可以不用
from sklearn import preprocessing  # 用于正则化
import numpy as np 
preprocessor = mz.preprocessors.BasicPreprocessor() 

ImportError: cannot import name 'Layer' from 'keras.engine' (/home/fxy0913@corp.sse.tongji.edu.cn/.conda/envs/blip/lib/python3.9/site-packages/keras/engine/__init__.py)

In [2]:
import torch 
import torch.nn as nn


class DSSM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, dropout):
        super(DSSM, self).__init__()
        self.embed = nn.Embedding(vocab_size, embedding_dim)
        self.fc1 = nn.Linear(embedding_dim, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 64)
        self.dropout = nn.Dropout(dropout)

    def forward(self, a, b):
        a = self.embed(a).sum(1)
        b = self.embed(b).sum(1)

        a = self.dropout(torch.tanh(self.fc1(a)))
        a = self.dropout(torch.tanh(self.fc2(a)))
        a = self.dropout(torch.tanh(self.fc3(a)))

        b = self.dropout(torch.tanh(self.fc1(b)))
        b = self.dropout(torch.tanh(self.fc2(b)))
        b = self.dropout(torch.tanh(self.fc3(b)))

        cosine = torch.cosine_similarity(a, b, dim=1, eps=1e-8)   # 计算两个句子的余弦相似度
        return cosine
    
    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                torch.nn.init.xavier_uniform_(m.weight)





/home/fxy0913@corp.sse.tongji.edu.cn/.conda/envs/blip/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
from transformers import BertTokenizer
import torch
def init_tokenizer():
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    tokenizer.add_special_tokens({'bos_token':'[DEC]'})
    tokenizer.add_special_tokens({'additional_special_tokens':['[ENC]']})       
    tokenizer.enc_token_id = tokenizer.additional_special_tokens_ids[0]  
    return tokenizer
tokenizer = init_tokenizer()
t_list = ['this is a model of mine','this is a model of yours','']
text1 = tokenizer(t_list,padding=True, return_tensors="pt")
print(text1.input_ids)
caps_len = []
for i in range(text1.attention_mask.shape[0]):
    caps_len.append(torch.count_nonzero(text1.attention_mask[i]).item())

caps_len = torch.tensor(caps_len)
print(caps_len)
# text2 = tokenizer('this is a model of mine', padding='longest', truncation=True, max_length=40, return_tensors="pt")
# print(text1.input_ids)
# print(text2.input_ids)
# model = DSSM(30522, 10, 0.2)
# model._init_weights()
# print(model(text1.input_ids,text2.input_ids))

tensor([[ 101, 2023, 2003, 1037, 2944, 1997, 3067,  102],
        [ 101, 2023, 2003, 1037, 2944, 1997, 6737,  102],
        [ 101,  102,    0,    0,    0,    0,    0,    0]])
tensor([8, 8, 2])


In [9]:
caption = ['12345','122222','11111']
print(caption[0])

12345


In [14]:
from torch.nn import CrossEntropyLoss
from torch import tensor
labels = [tensor([[-100,255,455,555,677,344,342]]),tensor([[-100,255,455,555,677,344,342]])]
a = torch.rand(1,6,30524)
for label in labels:
    label = label[:,1:].contiguous()
    print(label)
    loss_fct = CrossEntropyLoss(reduction='mean', label_smoothing=0.1) 
    now_lm_loss = loss_fct(a.view(-1, 30524), label.view(-1))
    print(now_lm_loss.item())



tensor([[255, 455, 555, 677, 344, 342]])
10.448413848876953
tensor([[255, 455, 555, 677, 344, 342]])
10.448413848876953


In [26]:
import torch 
from torch.nn.utils.rnn import pad_sequence
# import torch.nn.functional as F
a = torch.rand(19,15)#seq_num * seq_len
# a_list = list(torch.chunk(a, a.shape[0], dim = 0))
c = torch.rand(31,17)
# c_list = list(torch.chunk(c, c.shape[0], dim = 0))
# print(c)
list1 = [a,c]
all_list = []
# pad_sequence(list1)
# print(list1.shape())
for item in list1:
    all_list += list(torch.chunk(item, item.shape[0], dim = 0))
# all_list = [item.squeeze(0) for item in all_list]
print(pad_sequence([item.squeeze(0) for item in all_list], batch_first=True).shape)

# print(torch.cat(list1,dim=0))
# print(a)
# b = a[:,-1,:]
# d = c[:,-1,:]
# print(b)
# b = torch.max (a,-1)
# print(b)
# print(b.indices.shape)
# # c = torch.rand(1,5)
# output = F.cosine_similarity(b,d)
# print(output)
# print(b.shape)

17
torch.Size([50, 17])


In [1]:
import torch
from torch import tensor
label = tensor([[2551,2158,2012,25963,4713,102]])
shaped_prediction_score = torch.rand(1,6,30524)
score = shaped_prediction_score.view(-1,30524)


def self_loss(score,):


NameError: name 'tensor' is not defined

In [11]:
for content in caption:
    # print(i)
    print(content)

12345
122222
11111


In [8]:
from torch import tensor
import torch
a = tensor([[  101,  7661,  8917,  1106,  1103,  2394,  1107,  3461,   102,     0],
        [  101,  1109,  2084, 18884,  1116,  1103,  3181,  1107,  2290,   102],
        [  101,  6309,  1116,  1132,  1139,  5095,  5735,   102,     0,     0]])
print(a.shape)
# print(torch.split(a,[1,a.shape[1],a.shape[-1]],dim=0))
print(a[1])

torch.Size([3, 10])
tensor([  101,  1109,  2084, 18884,  1116,  1103,  3181,  1107,  2290,   102])


In [25]:
import torch.nn.functional as F
result1 = torch.randn(1,9,30524)
result2 = torch.randn(1,9,30524)
result3 = torch.randn(1,9,30524)
res_list = []
res_list.append(torch.max(result1,-1).indices)
res_list.append(torch.max(result2,-1).indices)
res_list.append(torch.max(result3,-1).indices)
print(res_list)
all_reg_loss_list = []
main_idx = 0
for main_idx in range(0,len(res_list)):
    print(main_idx)
    mainTensor = res_list[main_idx]
    for res_new in res_list[main_idx+1:]:
        print("inside")
        print(res_new)
        output = F.cosine_similarity(mainTensor.float(),res_new.float())
        print(output)
        # print(tensor.sum(output,1))
        # print(output)
        all_reg_loss_list.append(output)
print(all_reg_loss_list)
sum_reg_loss = torch.zeros_like(all_reg_loss_list[0])
for reg_loss in all_reg_loss_list:
    sum_reg_loss += reg_loss
print(sum_reg_loss)


[tensor([[10094, 13308, 27979, 27243,  5266, 22096, 19693, 13603, 26285]]), tensor([[18413,  2657, 21581, 16733,    86, 22866, 11966, 27904, 14086]]), tensor([[16133,  7627, 19829, 10808, 23843, 21130, 29533, 14019, 28984]])]
0
inside
tensor([[18413,  2657, 21581, 16733,    86, 22866, 11966, 27904, 14086]])
tensor([0.8855])
inside
tensor([[16133,  7627, 19829, 10808, 23843, 21130, 29533, 14019, 28984]])
tensor([0.8836])
1
inside
tensor([[16133,  7627, 19829, 10808, 23843, 21130, 29533, 14019, 28984]])
tensor([0.8004])
2
[tensor([0.8855]), tensor([0.8836]), tensor([0.8004])]


In [36]:
a = torch.ones([1,9,30524])
b = torch.ones([1,9,30524])
b = torch.cat([a,b],0)
a = tensor([10121])
b = tensor([123])
print(a/21)
print(b.size())
# print(b[1].size())
print(torch.cat([a,b]))

tensor([481.9524])
torch.Size([1])
tensor([10121,   123])


In [38]:
# a = tensor([1,2])
# print(a.item())


ValueError: only one element tensors can be converted to Python scalars

In [2]:
import torch
from torch import tensor
import json
def delete_duplicate(data):
    immutable_dict = set([str(item) for item in data])
    data = [eval(i) for i in immutable_dict]
    return data
def unique_dicts(data_list: list):
    data_json_set = set(json.dumps(item) for item in data_list)
    return [json.loads(item) for item in data_json_set]

print("a = ", a) 
#a = [{'image_id': 0,'phrase_list':[{'caption':'data','tensor':a},{'caption':'data','tensor':a},{'caption':'data1','tensor':a}]},]
a = [a,a,a,a,a,a,tensor([[1,2,3,4]])]
b = list(set(a))
# b = delete_duplicate(a[0]['phrase_list'])
print(b)

a =  tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.

In [8]:
import numpy as np
import torch
from torch import tensor
import json
a = torch.ones([1, 577]) 
a[0][0]=0
a[0][123]=0
a[0][257]=0
a_list=[]
b_list=[]
bnew={"caption":"hhhh","tensor":a.numpy().tolist()}
b_list.append(bnew)
b_list.append(bnew)
a_list.append({"image_id":245,"phrase_list":b_list})
print(a.numpy().tolist())
with open("1.json","w") as f1:
    json.dump(a_list,f1)
with open("1.json","r") as f:
    nwe = json.load(f)
print(torch.from_numpy(np.array(nwe[0]["phrase_list"][0]["tensor"])))

[[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0

In [14]:
a = torch.ones([2, 1, 577]) 
a_list.append(a)
a_list.append(a)
a_list.append(a)
print(a_list[1][0].size())

torch.Size([1, 577])


In [10]:
import torch
import torch.nn.functional as F
a = torch.tensor([0])
print(180.6//(180.6//3.657))
prediction_res = torch.randn(15,8)
print(prediction_res[8])
F.cosine_similarity(prediction_res[7].unsqueeze(0).float(),prediction_res[8].unsqueeze(0).float())

3.0
tensor([ 0.8847, -0.6185,  1.0276,  0.0298,  0.5165, -0.2820, -0.5032,  1.0705])


tensor([0.0861])

In [ ]:
a = torch.randn(1,8,30524)
a = torch.argmax(a,dim=2)
print(a)

: 

In [2]:
import json
ann_root = '/home/hcui25/Research/BLIP-MultiDecoder/annotation'
filename = 'dense_train.json'
annotation = json.load(open(os.path.join(ann_root,filename),'r'))
tf_idf_name = 'dense_train_predicate_tfidf_score_2.json'
corresponding_tf_idf = json.load(open(os.path.join(ann_root,tf_idf_name),'r'))

In [6]:
import random
ann = annotation[2324]#根据index获取annotation
match_tf_idf = corresponding_tf_idf[2324]
tf_list = []
for i,(phrase) in enumerate(ann['phrase_list']):
    # print(phrase)
    above_predicate = '' if i==0 else match_tf_idf['predicate_tf_idf_score'][i-1]['predicate']
    tf_idf_score = match_tf_idf['predicate_tf_idf_score'][i]
    additional_similar_values = 0.3 if tf_idf_score['predicate'] == above_predicate else 0.1
    tf_idf_score = match_tf_idf['predicate_tf_idf_score'][i]
    print(tf_idf_score)
    if tf_idf_score['tf_idf_score']< 0.4 and random.uniform(tf_idf_score['tf_idf_score'], 1) - additional_similar_values < 0.55:
        print('select!')
        continue
    tf_list.append(tf_idf_score)
print(tf_list)


{'predicate': 'has', 'tf_idf_score': 0.24428512292276455, 'original_phrase': 'brown bear has brown hat'}
select!
{'predicate': 'in', 'tf_idf_score': 0.17412517402626643, 'original_phrase': 'beige bear in box'}
select!
{'predicate': 'in', 'tf_idf_score': 0.17412517402626643, 'original_phrase': 'brown bear in box'}
select!
{'predicate': 'under', 'tf_idf_score': 0.1751989439614817, 'original_phrase': 'white table under beige bear'}
{'predicate': 'for', 'tf_idf_score': 0.23914875653791917, 'original_phrase': 'the box for brown bear'}
select!
{'predicate': 'has', 'tf_idf_score': 0.24428512292276455, 'original_phrase': 'beige bear has brown nose'}
{'predicate': 'has', 'tf_idf_score': 0.24428512292276455, 'original_phrase': 'brown bear has eye'}
select!
{'predicate': 'has', 'tf_idf_score': 0.24428512292276455, 'original_phrase': 'beige bear has leg'}
{'predicate': 'has', 'tf_idf_score': 0.24428512292276455, 'original_phrase': 'brown bear has foot'}
select!
{'predicate': 'has', 'tf_idf_score':